### ISSUE TITLE
[New Feature] 인증 관련 API

### ISSUE THREAD

**Issue by njs03332** [ssm0318/WhoamI-Today-backend#1]
- 회원가입
- 로그인
- 로그아웃

**Comment by GooJinSun** [comment]
제가 이전에 장고 알못이라 jwt 세팅을 하면서 놓쳤던 부분이 있는데요,
혹시 장고에서 jwt 토큰을 `setCookie`로 함께 넘겨 줄 수 있는지 검토 가능할까요?🙏🏻

- [JWT token as HttpOnly cookie in Django](https://www.procoding.org/jwt-token-as-httponly-cookie-in-django/)
- [How to store JWT tokens in HttpOnly cookies with DRF djangorestframework-simplejwt package?](https://stackoverflow.com/questions/66247988/how-to-store-jwt-tokens-in-httponly-cookies-with-drf-djangorestframework-simplej)

현재는 `/user/token`으로 로그인 하면 access, refresh 토큰을 응답값으로 넘겨주고, 그 토큰 값을 클라이언트에서 브라우저 쿠키에 저장해 관리하는 방식으로 되어있는데, 이 방식은 XSS 에 취약해서 HTTP Only cookie로 세팅해주는 게 좋다고 하더라구요! 참고: [기록차 남겨두었던 이전 이슈](https://github.com/GooJinSun/diivers/issues/216)
