### ISSUE TITLE
[New Feature] 노티 관련 수정사항 구현

### ISSUE THREAD

**Issue by njs03332** [ssm0318/WhoamI-Today-backend#110]
![스크린샷 2024-02-04 오전 8 52 33](https://github.com/GooJinSun/WhoAmI-Today-backend/assets/25769209/91d368f7-b407-4f3c-962b-95e0b0e58de5)
- 30일동안만 보관
- 유사한 노티 묶어서 보여주기: ‘xx, xx and others ~’
- 1:1 채팅으로 redirection
등등..

**Comment by ssm0318** [comment]
<Types of Notifications (as of 240204)>

Account
- message_ko=f'{requester.username}님이 친구 요청을 보냈습니다.'
- message_en=f'{requester.username} has requested to be your friend.'

- message_ko=f'{requester.username}님과 친구가 되었습니다.'
- message_en=f'You are now friends with {requester.username}.'

Comment
- message_ko=f'{actor_name_ko} 회원님의 댓글에 답글을 남겼습니다: "{content_preview}"'
- message_en=f'{actor_name_en} has replied to your comment: "{content_preview}"'

- message_ko=f'회원님의 {feed_type_ko}에 달린 댓글에 새로운 답글이 달렸습니다: "{content_preview}"'
- message_en=f'There\'s a new reply to the comment on your {feed_type_en}: "{content_preview}"'

- message_ko = f'{actor_name_ko} 회원님의 {origin_target_name_ko}에 댓글을 남겼습니다: "{content_preview}"'
- message_en = f'{actor_name_en} has commented on your {origin_target_name_en}: "{content_preview}"'

- message_ko=f'회원님이 댓글을 남긴 {origin_target_name_ko}에 새로운 댓글이 달렸습니다: "{content_preview}"'
- message_en=f'There\'s a new comment on the {origin_target_name_en} you commented on: "{content_preview}"'
 
Feed
- message_ko=f'똑똑똑! {requester.username}님으로부터 질문이 왔어요!: "{content_preview}"'***
- message_en=f'Knock knock! {requester.username} has sent you a question!: "{content_preview}"'***

- message_ko=f'{actor.username}님이 회원님이 보낸 질문에 답했습니다: "{content_preview}"'
- message_en=f'{actor.username} has responded to your question: "{content_preview}"'

Like
- message_ko = f'{actor_name_ko} 회원님의 댓글을 좋아합니다: "{content_preview}"'***
- message_en = f'{actor_name_en} likes your comment: "{content_preview}"'***

- message_ko = f'{actor_name_ko} 회원님의 답변을 좋아합니다: "{content_preview}"'***
- message_en = f'{actor_name_en} liked your response: "{content_preview}"'***

Tag (deprecated)
- message = f'{actor_name} 댓글에서 회원님을 언급했습니다.'

***: 노티가 합쳐지는 경우들

**Comment by ssm0318** [comment]
## Variations

[Question Receive]
- 똑똑똑! {user_a}님으로부터 질문이 왔어요!: {content_preview}
- 똑똑똑! {user_a}님과 {user_b}님으로부터 질문이 왔어요!: {content_preview}
- 똑똑똑! {user_a}님, {user_b}님, 외 {N}명의 친구로부터 질문이 왔어요!: {content_preview}
- Knock knock! {user_a} has sent you a question!: {content_preview}
- Knock knock! {user_a} and {user_b} have sent you a question!: {content_preview}
- Knock knock! {user_a}, {user_b}, and {N} other friends have sent you a question!: {content_preview}

[Comment Like]
- {user_a}님이 회원님의 댓글을 좋아합니다: {content_preview}
- {user_a}님과 {user_b}님이 회원님의 댓글을 좋아합니다: {content_preview}
- {user_a}님, {user_b}님, 외 {N}명의 친구가 회원님의 댓글을 좋아합니다: {content_preview}
- {user_a} liked your comment: {content_preview}
- {user_a} and {user_b} liked your comment: {content_preview}
- {user_a}, {user_b}, and {N} other friends liked your comment: {content_preview}

[Response LIke]
- {user_a}님이 회원님의 답변을 좋아합니다: {content_preview}
- {user_a}님과 {user_b}님이 회원님의 답변을 좋아합니다: {content_preview}
- {user_a}님, {user_b}님, 외 {N}명의 친구가 회원님의 답변을 좋아합니다: {content_preview}
- {user_a} liked your response: {content_preview}
- {user_a} and {user_b} liked your response: {content_preview}
- {user_a}, {user_b}, and {N} other friends liked your response: {content_preview}
