### ISSUE TITLE
[Bug] Error message

### ISSUE THREAD

**Issue by ssm0318** [ssm0318/WhoamI-Today-backend#146]
Sign up 과정에서 (아마 기존에 있는 이메일로 가입을 시도했을 경우) 오류가 나면 "Email not valid" error 대신 "User not found" error이 뜹니다.

**Comment by njs03332** [comment]
지금은 에러메시지 제대로 뜨는 것 같아요! 
혹시 계속 이슈 발생하면 다시 열어주세요 일단 close 하겠습니당~~
@ssm0318 

![스크린샷 2024-08-24 오후 3 05 18](https://github.com/user-attachments/assets/36990b16-5f45-4650-bd54-43e254fd6fb5)

**Comment by GooJinSun** [comment]
요고 혹시 다시 재현되면, 브라우저 쿠키 날리고 다시 시도해봐주세요~
