### ISSUE TITLE
[Refactoring] github security alert

### ISSUE THREAD

**Issue by GooJinSun** [ssm0318/WhoamI-Today-backend#147]
- [x] django: upgrade to `~>3.2.14`
- [x] Django: upgrade to `~>3.2.15`
<img width="471" alt="image" src="https://github.com/GooJinSun/WhoAmI-Today-backend/assets/37523788/bdd875b1-3612-4e4b-b9c0-eae2e5b4ffdd">

**Comment by ssm0318** [comment]
https://www.djangoproject.com/download/ 이거 토대로 4.2.10으로 업그레이드 했습니다.
