### ISSUE TITLE
[New Feature] comment report

### ISSUE THREAD

**Issue by ssm0318** [ssm0318/WhoamI-Today-backend#150]

**Comment by njs03332** [comment]
@ssm0318 요건 어디서 구현된 건가용? #145 에서는 따로 150번이 태그가 안되어있어서 여쭤봅니당 ㅎㅎ

**Comment by ssm0318** [comment]
@njs03332 아 제가 놓친 부분이 있을수도 있는데 comment report를 구현하려고 봤더니 제가 content report를 구현하면서 이미 구현을 한 것 같더라고요 ....?

**Comment by njs03332** [comment]
아하 그렇군요 네넹 !! :)
