### ISSUE TITLE
[Bug] 프로필 사진을 등록해도 프로필 사진이 보이지 않습니다

### ISSUE THREAD

**Issue by GooJinSun** [ssm0318/WhoamI-Today-backend#203]
**내용**
프로필 사진을 등록해도 프로필 사진이 보이지 않습니다
**버그 재현 절차**

1. 회원가입 시 프로필 사진 등록
2. /friends 탭 및 하단 탭, 마이페이지에서 프로필 사진 확인
3.

프론트에서 요청하는 프로필 이미지 URL: https://diivers.world/media/profile_images/sunny__9__.png
404 NOT Found가 뜸

**정상 결과**
등록한 프로필 사진이 보여야 합니다
**이미지**
![image](https://github.com/GooJinSun/WhoAmI-Today-backend/assets/37523788/95249e7d-d169-4b88-b312-5d72474fd8d6)

**테스트 환경**
데스크탑 / 모바일 / 브라우저 등

**Comment by GooJinSun** [comment]
로컬에서 서버 돌릴 때 워닝이 있는데, 관련있는 부분인 거 같아 로깅합니다
```
WARNINGS:
?: (staticfiles.W004) The directory '/Users/user/Dev/WhoAmI-Today-backend/adoorback/adoorback/adoorback/static' in the STATICFILES_DIRS setting does not exist.
```
<img width="750" alt="image" src="https://github.com/GooJinSun/WhoAmI-Today-backend/assets/37523788/ffdff590-74ad-46fa-829c-489688fe8e1e">

**Comment by ssm0318** [comment]
nginx 설정 이슈였습니당...!
