### ISSUE TITLE
[Bug] Invalid HTTP_HOST header (server error)

### ISSUE THREAD

**Issue by njs03332** [ssm0318/WhoamI-Today-backend#215]
**내용**
<img width="1084" alt="스크린샷 2024-04-27 오전 8 40 46" src="https://github.com/GooJinSun/WhoAmI-Today-backend/assets/37107740/1d0c1fa5-c6c8-4c34-bc20-a5558b90fb45">
<img width="1091" alt="스크린샷 2024-04-27 오전 8 43 16" src="https://github.com/GooJinSun/WhoAmI-Today-backend/assets/37107740/86f615f5-25cf-40fe-8686-9e184d54578e">

**버그 재현 절차**

1.
2.
3.

**정상 결과**

**이미지**

**테스트 환경**
데스크탑 / 모바일 / 브라우저 등

**Comment by ssm0318** [comment]
그거 제가 뭐 해결하려다가 난거 같은데 아직도 그러나요? 이제 해결됐으텐데
