### ISSUE TITLE
[Bug] friend list API 버그 - note read API 추가

### ISSUE THREAD

**Issue by njs03332** [ssm0318/WhoamI-Today-backend#218]
**내용**
<img width="854" alt="스크린샷 2024-04-27 오후 5 16 05" src="https://github.com/GooJinSun/WhoAmI-Today-backend/assets/37107740/62b3ac12-5ccb-4701-984d-1cc6afd2e3ff">

**버그 재현 절차**

1.
2.
3.

**정상 결과**

**이미지**

**테스트 환경**
데스크탑 / 모바일 / 브라우저 등

**Comment by njs03332** [comment]
note에 read 관련 모듈들 추가 필요 (feature)

**Comment by GooJinSun** [comment]
`/api/user/friends/?type=has_updates` 500 에러 남
<img width="555" alt="image" src="https://github.com/GooJinSun/WhoAmI-Today-backend/assets/37523788/6b99e970-d41d-4439-863c-92da068980f0">

- `sunny__9__` 계정에서만 재현됨(지나, 유진, 유리 김 계정에서는 재현 안됨)

**Comment by njs03332** [comment]
~@GooJinSun 님 요고 에러메시지가 기록이 안되어 있어서 원인 확인이 어려운데요..~
~혹시 한 번만 더 시도해서 로그가 남게 해주실 수 있을까용 ?! (지금은 에러나면 로그가 잘 남겨지고 있는 것 같아요!)~
는 문제를 찾은 것 같아용 :)
