### ISSUE TITLE
[Bug] friend page에서 note 정렬

### ISSUE THREAD

**Issue by njs03332** [ssm0318/WhoamI-Today-backend#220]
**내용**
- 친구 페이지에 들어가면 note가 최신순이 아닌 역순으로 정렬되어있음 (내 페이지는 그렇지 않음)
**버그 재현 절차**

1.
2.
3.

**정상 결과**

**이미지**

**테스트 환경**
데스크탑 / 모바일 / 브라우저 등

**Comment by ssm0318** [comment]
@njs03332 이거 저 재현이 안돼요!

**Comment by njs03332** [comment]
오잉 그러네요 그 때는 왜그랬지.. 저도 재현 안돼서 이슈 닫겠습니당 ! 확인 감사해용
