### ISSUE TITLE
[Bug] 프로필 사진 변경 이후, 프로필 사진이 새로운 사진으로 업데이트되지 않는 버그

### ISSUE THREAD

**Issue by GooJinSun** [ssm0318/WhoamI-Today-backend#221]
**내용**
프로필 사진 변경 이후, 프로필 사진이 새로운 사진으로 업데이트되지 않는 버그

**버그 재현 절차**

1. 설정 > 프로필 사진 변경
2. 사진 등록
3. 저장
4. PATCH `/api/me` api call은 성공하지만, 이미지가 업데이트 되지 않습니다

**정상 결과**
새로 바뀐 프로필 이미지가 보여져야 합니다

**이미지**

https://github.com/GooJinSun/WhoAmI-Today-backend/assets/37523788/bc8d4e2a-12a5-45ca-86de-9f93ed2cc198

**테스트 환경**
데스크탑 / 모바일 / 브라우저 등

**Comment by ssm0318** [comment]
재현이 안 되는데, [요거](https://github.com/GooJinSun/WhoAmI-Today-backend/issues/203) 이후로 고쳐진게 아닌가 싶네요?!
