### ISSUE TITLE
[Bug] 하나의 게시글에 여러 사람이 게시글의 좋아요를 누르면, 첫번째 좋아요를 누른 사람 외에는 푸시 노티가 오지 않습니다

### ISSUE THREAD

**Issue by GooJinSun** [ssm0318/WhoamI-Today-backend#225]
**내용**
하나의 게시글에 여러 사람이 게시글의 좋아요를 누르면, 첫번째 좋아요를 누른 사람 외에는 푸시 노티가 오지 않습니다

**버그 재현 절차**
1. 이미 누군가 좋아요를 누른 게시글에 누군가 좋아요를 누릅니다
2. 푸시 노티가 오지 않습니다

**정상 결과**
첫번째 좋아요 누른 사람 외에도 좋아요가 눌리면 푸시 노티를 보내줘야 합니다

**이미지**

**테스트 환경**
데스크탑 / 모바일 / 브라우저 등

**Comment by ssm0318** [comment]
노티 자체가 업데이트 되지 않음. timestamp 새로 찍으면서 unread로 바꿔주기
