### ISSUE TITLE
[Bug] POST '/check_in' > availability가 null이거나 "" 일때 400 에러

### ISSUE THREAD

**Issue by koyrkr** [ssm0318/WhoamI-Today-backend#244]
**내용**

POST '/check_in' > availability가 null이거나 "" 일때 400 에러가 납니다!

아마 backend에서 정해진 값이 아니면 저장이 안되도록 해두신 것 같은데 빈 값을 허용해주시되, 값이 있다면 허용 값도 새로 다시 업데이트가 되어야할 것 같습니다.
(아래는 frontend에서 최신 피그마에 맞게 값들 업데이트 해둔 내용이니 참고해주세여)

```typescript
export enum Availability {
  available = 'available',
  busy = 'busy',
  might_get_distracted = 'might_get_distracted',
  urgent_only = 'urgent_only',
  about_to_sleep = 'about_to_sleep',
  studying = 'studying',
  in_transit = 'in_transit',
  feeling_social = 'feeling_social',
  feeling_quiet = 'feeling_quiet',
}
```

**버그 재현 절차**

1. feat/issue-391 브랜치에서 check-in > availability 선택 안하고 저장
2.
3.

**정상 결과**

availability가 null이거나 ""이어도 저장이 되어야합니다~

**이미지**

<img width="620" alt="Screenshot 2024-05-18 at 2 05 19 PM" src="https://github.com/GooJinSun/WhoAmI-Today-backend/assets/42240753/6f33febd-32f3-4214-854e-1a31242d09f3">

현재 피그마 참고
<img width="588" alt="Screenshot 2024-05-18 at 2 01 20 PM" src="https://github.com/GooJinSun/WhoAmI-Today-backend/assets/42240753/13af36f3-4975-4084-971c-7df1f0cd121a">

**테스트 환경**
데스크탑 / 모바일 / 브라우저 등

**Comment by njs03332** [comment]
@koyrkr 님, 요고 `availability` 필드를 아예 주지 않으면 자동으로 디폴트값인 'no_status'로 들어가게 되어있는데요, 수정 필요한 부분일까용?
예)
```json
{"mood": "🎀", "description": "I am available", "track_id": "11dFghVXANMlKmJXsNCbNl"}
```

**Comment by koyrkr** [comment]
@njs03332 아하 아예 안드리면 되는거군요! 그럼 아예 안보내겠슴다! 확인해주셔서 감사해유~ 😁

그런데 제가 mood, description, track_id의 경우는 없으면 빈 스트링으로 보내고 있었는데 그건 그대로 저장이 잘 되는 거 같드라구요! 그것들은 그대로 둬도 상관없는건가여?

**Comment by njs03332** [comment]
@koyrkr 네네 맞습니당 !! `availability`의 경우에는 없는 경우 `no_status`로 디폴트가 설정되도록 해둬서 요것만 예외이고 나머지는 빈 필드로 넣어도 되게 설정되어있습니다!

**Comment by koyrkr** [comment]
@njs03332 오 네~~! 알겠습니다! frontend쪽에 no_status 값을 추가하는 것도 필요하겠네여! 감사합니다~~

**Comment by koyrkr** [comment]
@njs03332 그런데 혹시 `no_status` 라는 디폴트 값이 왜 있는건가요? 혹시 예전 기획에 기반된 것이라면 혹시 수정이 가능할지요..! (위에서 좋다고 말해두고 바로 말을 바꿔버려서 죄송함다..)

이유는, 프론트 입장에서는 check_in을 조회하고 availability가 no_status로 오면, 다시 (없는것처럼..?) 예외처리를 해야하는 번거로움이 있어서 아예 다른 값들처럼 빈 필드 허용을 하게 수정해주시면 아주 좋을 것 같슴다...! 

천천히 확인해보시고 알려주세요~~!!
