### ISSUE TITLE
[New Feature] like한 사람들 search API 추가

### ISSUE THREAD

**Issue by koyrkr** [ssm0318/WhoamI-Today-backend#253]
<img width="308" alt="Screenshot 2024-05-25 at 4 50 00 PM" src="https://github.com/GooJinSun/WhoAmI-Today-backend/assets/42240753/021536c6-b708-422e-8e19-46661690dbea"/>

Note, Response에 대해서 like 한 사람들 목록을 볼 수 있는 화면에서 이름으로 search 할 수 있는 API가 필요합니다

**Comment by ssm0318** [comment]
엇 친구수가 많지 않을 것 같아서 search bar 자체를 없애는 방향으로 가는게 좋을 거 같아요! 디자인 디테일 미리 신경 못 써서 죄송합니다!

**Comment by ssm0318** [comment]
확인 후 이슈 닫아주세요~
