### ISSUE TITLE
[Refactoring] hard delete 할 곳 혹은 해야할 곳 찾아서 policy 변경

### ISSUE THREAD

**Issue by ssm0318** [ssm0318/WhoamI-Today-backend#266]

**Comment by njs03332** [comment]
https://www.notion.so/jinsungoo/soft-hard-delete-d0029a686a004f6286116cb36993bbee?pvs=4

<img width="1013" alt="스크린샷 2024-10-05 오후 3 13 55" src="https://github.com/user-attachments/assets/41715b2a-b9e6-4601-8a29-068939563371">

**Comment by njs03332** [comment]
note image -> hard delete
