### ISSUE TITLE
[Bug] 비밀 댓글을 남기면 게시글 작성자 이외의 사람에게 알림이 감

### ISSUE THREAD

**Issue by koyrkr** [ssm0318/WhoamI-Today-backend#274]
**내용**

비밀 댓글을 남기면 게시글 작성자 이외의 사람에게 알림이 감

**버그 재현 절차**

1.
2.
3.

**정상 결과**

비밀 댓글을 남기면 게시글 작성자 이외의 사람에게 알림 자체가 가지 말아야 함

**이미지**

**테스트 환경**
데스크탑 / 모바일 / 브라우저 등

**Comment by koyrkr** [comment]
![IMG_6618](https://github.com/GooJinSun/WhoAmI-Today-backend/assets/42240753/777681e6-f6bc-405e-8661-4781f02db4ae)

notification 목록에도 존재함

There's a new comment on the note you commented on "작성했니~??" 
이건 다른 작성자 게시글로 비밀댓글로 단 내용인데 저에게 보이고 있습니다~

**Comment by njs03332** [comment]
#297 과 중복으로 닫습니당
