### ISSUE TITLE
[Bug] 푸시 알림의 질문 내용이 언어 설정과 다르게 옴

### ISSUE THREAD

**Issue by koyrkr** [ssm0318/WhoamI-Today-backend#275]
**내용**

영어 설정으로 되어있음에도 불구하고, 푸시 알림의 질문 내용이 한글로 오고 있음!

**버그 재현 절차**

1.
2.
3.

**정상 결과**

**이미지**
![IMG_6619](https://github.com/GooJinSun/WhoAmI-Today-backend/assets/42240753/521b89f0-48c0-4352-9bc9-ae093adad229)

**테스트 환경**
데스크탑 / 모바일 / 브라우저 등

**Comment by ssm0318** [comment]
@koyrkr 이거 푸시 알림만 언어가 다르고 일반 노티에서는 제대로 오고 있는건가요?
