### ISSUE TITLE
[New Feature] 댓글 개수 (대댓글 개수 포함)

### ISSUE THREAD

**Issue by njs03332** [ssm0318/WhoamI-Today-backend#276]
- 현재는 댓글 개수만 counting되어 보임
- 대댓글까지 포함하여 개수를 보내주어야 함 (프론트에서는 pagination 되어서 오기 때문에 직접 count할 수 없음)

**Comment by ssm0318** [comment]
pagination 되더라도 api 응답 가장 상단에 'count'라는 필드가 내려오지 않나요? @njs03332

**Comment by njs03332** [comment]
앗 그런가요 @GooJinSun 님 요거 확인 부탁드릴 수 있을까요~? count 필드로 가능한 거면 백엔드 추가 작업 필요 없을지..!

**Comment by GooJinSun** [comment]
@njs03332 @ssm0318 

현재는 comment 개수만 오고, reply(대댓글)은 미포함 상태로 `count`가 내려오고 있네요
기획적으로 reply 개수는 포함될 필요없나요?

cc. @dbwk18
