### ISSUE TITLE
[New Feature] 읽지 않은 노티가 있는지 확인 필요

### ISSUE THREAD

**Issue by koyrkr** [ssm0318/WhoamI-Today-backend#284]
<img width="429" alt="Screenshot 2024-07-13 at 4 42 29 PM" src="https://github.com/user-attachments/assets/f94fa4f3-4850-41e2-937a-0c5ccab349ae">

새로운 노티가 있을때 상단바 오른쪽 노티 아이콘 옆에 뱃지를 붙여줘야, 읽은 노티가 있는지 없는지를 유저가 확인할 수 있을 것 같습니다!
새로운 api를 만들어주셔도 좋고 기존 api 중 GET user/me 에 has_unread_noti 같은 값을 추가해주시면 작업할때 수월할 것 같습니다~!

**Comment by ssm0318** [comment]
@koyrkr 지금 user/me가 이미 unread_noti를 내려주고 있는데 boolean 값으로 따로 내려달라고 하시는게 맞나요?

**Comment by koyrkr** [comment]
@ssm0318 오 unread_noti가 있었네요 레전드! 이거 쓰면 될거같아요 감사합니다~!
