### ISSUE TITLE
[Bug] 댓글 작성 API(POST `api/comments/`)의 응답속도가 너무 느립니다

### ISSUE THREAD

**Issue by GooJinSun** [ssm0318/WhoamI-Today-backend#316]
**내용**
재현시 5초 이상 소요될 때가 있습니다
<img width="1054" alt="스크린샷 2024-08-28 오전 9 43 22" src="https://github.com/user-attachments/assets/a9437ff3-010c-4344-aba9-7f4e7cc98396">

**버그 재현 절차**

1.
2.
3.

**정상 결과**

**이미지**

**테스트 환경**
데스크탑 / 모바일 / 브라우저 등

**Comment by njs03332** [comment]
+ 좋아요 API도 같이 확인

**Comment by njs03332** [comment]
@GooJinSun 님 호옥시 이게 어떤 상황에서 5초 이상 소요되면서 느려졌었는지 기억이 나시거나 파악이 되셨던 부분이 있으셨나용...? 재현이 잘 안되어서 여쭤봅니당

**Comment by GooJinSun** [comment]
@njs03332 오호 유리님 다시 재현해보려고 했는데 지금은 재현이 안되네요

**Comment by njs03332** [comment]
오 그렇군요 다행입니당..!! 혹시 재현된다면 다시 제보 부탁드려용 일단 이슈 닫겠습니닷
