### ISSUE TITLE
[Bug] notification seed 데이터 에러

### ISSUE THREAD

**Issue by koyrkr** [ssm0318/WhoamI-Today-backend#326]
**내용**

**버그 재현 절차**

1.
2.
3.

**정상 결과**

**이미지**

https://github.com/user-attachments/assets/38dd4fbc-0ff9-40c7-afa0-fcc16ead4b91

![Screenshot 2024-08-31 at 4 46 01 PM](https://github.com/user-attachments/assets/5b0cbc88-c7de-4955-9c43-f6ab370a73ba)

ResponseRequest 타입인데 question_content가 null이어서 notification serializer에서 문제가 생기는 것 같습니다~!

**테스트 환경**
데스크탑 / 모바일 / 브라우저 등

**Comment by njs03332** [comment]
앗 이거 #319 요기서 은근슬쩎 작업했어요..!
