### ISSUE TITLE
[Bug] daily noti 시차 있는 경우(?) 노티가 두 개 와요

### ISSUE THREAD

**Issue by ssm0318** [ssm0318/WhoamI-Today-backend#333]
**내용**
![image](https://github.com/user-attachments/assets/99c9ecc1-f0c9-4b60-a9f9-99abd00a1f85)

시간차를 두고 노티가 두개 오네요 시차가 있어사 그런건지 노티 시간대 설정을 뭔가 해서 그런건지..

**버그 재현 절차**

1.
2.
3.

**정상 결과**

**이미지**

**테스트 환경**
데스크탑 / 모바일 / 브라우저 등

**Comment by njs03332** [comment]
@ssm0318 흠 요거 DB를 봤을 때는 하루에 하나씩만 간 걸로 나오는데 혹시 저기 두 개가 어제랑 오늘 이렇게 따로따로 온 것은 아닌가용..? (버그 때문에 질문 내용은 계속 같게 왔음)
지금도 계속 하루에 두 개씩 오나요?

**Comment by njs03332** [comment]
<img width="617" alt="스크린샷 2024-09-07 오후 4 59 05" src="https://github.com/user-attachments/assets/58009c27-8272-450a-a075-08f0bbf35e02">
