### ISSUE TITLE
[Bug] 받은 질문 개수가 정확한지?

### ISSUE THREAD

**Issue by ssm0318** [ssm0318/WhoamI-Today-backend#334]
**내용**

[https://github.com/GooJinSun/WhoAmI-Today-frontend/issues/582](https://github.com/GooJinSun/WhoAmI-Today-frontend/issues/582) 받은 질문 개수가 35개로 표시되어있으나 실제로는 1개만 보임
--> 재오니가 답변 5개 남김
--> 재오니에게 남아있는 받은 질문 개수가 11개
<img width="502" alt="Screenshot 2024-09-06 at 5 57 14 PM" src="https://github.com/user-attachments/assets/ff0fc7cd-1a02-4641-9282-60b0f8ccf8ac">

**버그 재현 절차**

1.
2.
3.

**정상 결과**

**이미지**

**테스트 환경**
데스크탑 / 모바일 / 브라우저 등

**Comment by njs03332** [comment]
요거는 확인해보니 남은 개수가 맞는 것 같아요! 
재오니에게 response request가 총 17개가 왔고 그 중 두 개는 질문이 겹쳐서,
unique한 받은 질문 개수는 16개
이 중 5개에 답변함
-> 남은 질문 11개!!

혹시 이후에도 이상 있으면 말씀주세요~~
