### ISSUE TITLE
[Refactoring] 사용하지 않는 fcm_django_fcmdevice 테이블 삭제

### ISSUE THREAD

**Issue by koyrkr** [ssm0318/WhoamI-Today-backend#355]
- custom_fcm_customfcmdevice 테이블로 fcm 관련 정보 관리 할 수 있게 되었으므로 fcm_django_fcmdevice는 삭제 필요
- 일단 fcm_django_fcmdevice의 active는 모두 FALSE로 바꾸었고, 그럼에도 문제 없는 것 확인 완료
- 앞으로 새로 추가되는 fcm 정보는 어차피 custom_fcm_customfcmdevice 테이블에 저장될 것이므로 급한 이슈는 아님

**Comment by njs03332** [comment]
- deleted `fcm_django_fcmdevice` table in remote server
- fixed `/etc/postgresql/{version}/main/pg_hba.conf`  file due to psql access error
```shell
psql -U postgres -d whoamitoday
psql: error: FATAL: Peer authentication failed for user "postgres"
```
```
### /etc/postgresql/{version}/main/pg_hba.conf file
...
# "local" is for Unix domain socket connections only 
- local all all peer 
+ local all all md5
...
```
- table drop: `DROP TABLE IF EXISTS fcm_django_fcmdevice;`
