### ISSUE TITLE
[New Feature] Post에 reaction_user_sample 추가

### ISSUE THREAD

**Issue by koyrkr** [ssm0318/WhoamI-Today-backend#368]
현재 response나 note에서 like_user_sample 키값으로 좋아요 누른 유저 리스트를 내려주고 있는데요, (사진과 같이) 이모지 리액션에 대한 정보도 필요할 것 같습니다!

`reaction_user_sample` 이라는 키값으로 바꾸고, 원래 오던 `like_user_sample` 값에 

```
like: boolean;
emoji: string | null;
```

을 추가해주시면 좋을 것 같습니다. 예를 들어 다음과 같이 오면 될 것 같고, 순서는 최신 순서로 오면 될 것 같습니당!

```
reaction_user_sample: [
  id: 7,
  ...(이전에 보내주시던 정보와 동일)
  like: false, // 추가
  emoji: '😅' // 추가
]
```

**Comment by njs03332** [comment]
@koyrkr 
한 사람이 여러 개의 이모지를 누를 수 있어서, `emoji: list;` 가 되어야할 것 같아요!


추가로,
기존 like_user_sample에서는 가장 최근에 like를 누른 유저 3명을 반환했는데,
변경되는 스펙에서는 아래 중에 어떻게 반환하면 될까요? 
- like/emoji 통틀어서 최신 유저 3명
- like 최신 3명, emoji 최신 3명
- like 최신 3명, 각 emoji별 최신 3명
- ....?

like와 emoji를 누른 사람의 프로필사진이 작게 보이는 UI가 어떻게 되는지 혹시 확정되었을까요?

**Comment by koyrkr** [comment]
@njs03332 

> 한 사람이 여러 개의 이모지를 누를 수 있어서, emoji: list; 가 되어야할 것 같아요!

그런데 프론트 입장에서는 같은 유저가 남긴 이모지더라도 각각 나눠서 보내주시면 좋겠는데 가능하실까여? 

> 변경되는 스펙에서는 아래 중에 어떻게 반환하면 될까요?

통틀어서 최신 유저 3명이면 될 것 같습니다!

> like와 emoji를 누른 사람의 프로필사진이 작게 보이는 UI가 어떻게 되는지 혹시 확정되었을까요?

네 저는 저번 스크럼때 거의 확정되었다고 생각해서 작업중이었는데, 오늘중으로 작업한 내용 캡쳐해서 업로드해두겠습니다..!
텍스트로 간단히 말씀드려보자면, 유저의 프로필 사진이 최대 3개 보이고 (좋아요 눌렀던 사람들처럼) 각각의 프로필 사진 우측하단에 조그맣게 좋아요 아이콘이나 이모지 아이콘을 보여줄 예정입니다!
