### ISSUE TITLE
[New Feature] Post의 like, emoji reaction 리스트 API 추가

### ISSUE THREAD

**Issue by koyrkr** [ssm0318/WhoamI-Today-backend#370]
- Pagination 작업도 되어있어야할 것 같습니다!

**Comment by njs03332** [comment]
@koyrkr 
요것도 UI에 따라서 아래 두가지 방법 중 하나를 선택해야할 것 같은데요,
- 기존의 `notes/<int:pk>/likes/` API와 통합하여 like + reaction 전체 리스트 반환하는 API 생성
- `notes/<int:pk>/reactions/` API를 별도로 생성

post의 작성자가 like/reaction을 확인할 때, like를 누른 사람의 리스트 / reaction을 누른 사람의 리스트를 별개의 페이지에서 조회하는지, 같은 페이지에서 조회하는지 혹시 정해진 스펙이 있나용?

**Comment by koyrkr** [comment]
@njs03332 

같은 페이지에서 조회하게 될 것 같습니다! 어떤 post에 달린 like/emoji (프론트에서는 이걸 합쳐서 reaction이라고 부르고 있어요.. 저 혼자..) 를 합쳐서 보여주고, 그 합쳐진 영역을 눌렀을때 페이지를 이동하는거라 하나의 페이지로 이동할 것 같습니다! 

> 기존의 notes/<int:pk>/likes/ API와 통합하여 like + reaction 전체 리스트 반환하는 API 생성
notes/<int:pk>/reactions/ API를 별도로 생성

그래서 저는 의미상으로 (reaction = like + emoji라서..) reactions 가 들어간 endpoint를 쓰는게 어떨까 싶었고, 어쨌든 그 api endoint의 반환값으로는 like/emoji 정보들이 모두 내려와야할 것 같습니다!

혹시 말로는 이해가 안되신다면 제가 집에서 작업한 내용을 캡쳐해서 올려둘 수 도 있을 것 같슴다 편히 말씀해주셔요

**Comment by koyrkr** [comment]
<img width="378" alt="Screenshot 2024-10-19 at 2 17 30 PM" src="https://github.com/user-attachments/assets/de9a5616-98a6-4b4e-bf72-4108fbd0b2f8">

위 저 영역을 누르면 아래 페이지로 이동하게 될 것 같습니다~!
(데이터가 안맞는 것은 제가 임의로 테스트 데이터를 넣어서 작업해서 그렇습니다..! 참고만 해주세요!)

<img width="444" alt="Screenshot 2024-10-19 at 2 19 14 PM" src="https://github.com/user-attachments/assets/c190502d-73b7-4f6c-a052-e54c0ff45b7e">

@njs03332

**Comment by njs03332** [comment]
@koyrkr 
감사합니다 :)
용어의 혼동이 있을 것 같아서 추가로 말씀드리자면 백엔드 모델 구조상으로는 "이모지 리액션" 모델의 이름이 reaction이고, 여기서 필드 중 하나가emoji (text field)로 들어가있어요! 
그래서 백엔드에서 사용하는 필드명은 (아마도 대부분?) 기본적으로 reaction=이모지 리액션 을 기준으로 작성되어있으니까 참고해주세요!

**Comment by koyrkr** [comment]
@njs03332 넵 설명 감사합니다~! 참고하겠습니다 :)
