### ISSUE TITLE
[New Feature] Notification period setting

### ISSUE THREAD

**Issue by njs03332** [ssm0318/WhoamI-Today-backend#407]

**Comment by koyrkr** [comment]
@njs03332 

PATCH /user/me/ 에서 똑같이 주기를 바꿀 수 있으면 좋을 것 같습니다!
이렇게 noti_time과 같은 레벨에 noti_period_days가 들어간 형식으로 생각했습니다!

```typescript
 type DayOfWeek = 0 | 1 | 2 | 3 | 4 | 5 | 6;  // 0 = Sunday, 1 = Monday, etc.

 ...
  noti_time: string;
  noti_period_days: DayOfWeek[];
 ...

```

혹 더 나은 방향이 있다면 말씀해주세요 감사합니다~

**Comment by njs03332** [comment]
오오 네넹 조은 것 같습니닷 ! 
제가 잘 모르는뎅 type DayOfWeek 요 형식으로 정의하더라도 결국 요기서 Text 형식으로 들어가게 되는거죵?!
<img width="987" alt="스크린샷 2024-11-23 오전 11 39 32" src="https://github.com/user-attachments/assets/4f28912a-485e-452c-9ef4-b456fd24a0ba">

**Comment by koyrkr** [comment]
@njs03332 오 form data로 보내고 있다는 사실을 간과했네요 ㅠ

네 Text 형식이 맞는 것 같고 Value에는 [1,3,5] 같은 값이 들어가면 될 것 같습니다!

**Comment by njs03332** [comment]
넴넴 요렇게 가면 될 것 같아유!!
