### ISSUE TITLE
[Bug] 모먼트 좋아요의 노티 메시지

### ISSUE THREAD

**Issue by GooJinSun** [ssm0318/WhoamI-Today-backend#65]
**내용**
모먼트 좋아요에 대한 노티 메시지가 다음과 같이 옵니다
`message: "sunny liked your post: \"Moment object (3)\"`

![image](https://github.com/GooJinSun/WhoAmI-Today-backend/assets/37523788/5eedc044-d820-4ccc-a9c9-1cdb377c5901)
<img width="364" alt="image" src="https://github.com/GooJinSun/WhoAmI-Today-backend/assets/37523788/a5e0db04-72f9-4bd3-8c60-3f107971d875">

**정상 결과**
A님이 당신의 오늘의 순간?을 좋아합니다 등 적절한 메시지가 와야합니다
**이미지**

**테스트 환경**
데스크탑 / 모바일 / 브라우저 등

**Comment by njs03332** [comment]
요거 노티 문구 수정 작업 하시면서 해주실 수 있을까용 !! @h-yes-oo
