### ISSUE TITLE
[Bug] 로그인 시 사용자 이름으로 로그인이 안되는 현상

### ISSUE THREAD

**Issue by koyrkr** [ssm0318/WhoamI-Today-backend#72]
**내용**

로그인 시 사용자 이름으로 로그인이 안되고, 이메일로만 가능합니다!

**버그 재현 절차**

1. 로그인 시 제 이름 (gina) 입력
2. 비밀번호 입력 후 로그인 시도
3. 로그인 실패
4. 이메일 입력 (koyrkr@gmail.com) 
5. 비밀번호 입력 후 로그인 시도
6. 성공

**정상 결과**

gina + 비밀번호를 입력했을 때도 로그인이 성공되어야할 것 같습니다~!

**이미지**
<img width="441" alt="Screenshot 2023-09-02 at 16 22 15" src="https://github.com/GooJinSun/WhoAmI-Today-backend/assets/42240753/e83edd20-60df-4884-8c23-37aada1b7920">

**테스트 환경**
데스크탑 / 모바일 / 브라우저

**Comment by GooJinSun** [comment]
@koyrkr 오호 지나님 저는 유저네임으로 로그인이 잘되는데
혹시 어떤 환경(diivers.world/local)에서 테스트하신걸까요~?

https://github.com/GooJinSun/WhoAmI-Today-backend/assets/37523788/a8a20c2b-96a7-4d04-b537-3661665b5a71

**Comment by koyrkr** [comment]
<img width="814" alt="Screenshot 2023-09-02 at 17 48 24" src="https://github.com/GooJinSun/WhoAmI-Today-backend/assets/42240753/c05f61a0-93a5-415d-ad73-9d174ad2eeb4">
<img width="720" alt="Screenshot 2023-09-02 at 17 49 01" src="https://github.com/GooJinSun/WhoAmI-Today-backend/assets/42240753/34a755f6-f108-4172-a3f2-162338995871">

diivers.world에서 테스트했습니다! 
이렇게 실패를 하고 나서 바로 koyrkr@gmail.com 으로 테스트하면 바로 로그인이 잘 됩니다 😭

**Comment by GooJinSun** [comment]
사용자 이름 중에 대/소문자만 다른 유저네임이 있는 유저가 존재할 경우(gina, Gina) 로그인이 안되는 걸로 확인됨
