### ISSUE TITLE
[Bug] GET moment/{momentId}

### ISSUE THREAD

**Issue by koyrkr** [ssm0318/WhoamI-Today-backend#75]
**내용**

여기서 created_at이 오지 않아서 에러가 나고 있습니다!

**버그 재현 절차**

1. https://diivers.world/moments/{id} 접속
2. Uncaught RangeError: Invalid time value 에러 발생
3.

**정상 결과**

created_at이 잘 오면 해당 페이지로 잘 접속될 것으로 기대합니다!

**이미지**

**테스트 환경**
데스크탑 / 모바일 / 브라우저 등

**Comment by koyrkr** [comment]
https://github.com/GooJinSun/WhoAmI-Today-frontend/issues/162
해당 이슈와도 연결되어있는 이슈입니다! 노티의 redirect_url은 잘 오고 있습니다~

**Comment by njs03332** [comment]
#85 와 같은 이슈인 것 같아 close할게요!
