### ISSUE TITLE
[Bug] 친구 피드 API(`api/user/friends/today/`)에서 `created_at` 필드가 누락되는 버그

### ISSUE THREAD

**Issue by GooJinSun** [ssm0318/WhoamI-Today-backend#85]
**내용**
@h-yes-oo 혜수님 확인해보니 `api/user/friends/today/` API에서
게시글별로 `date`만 넘어오고 `created_at` 필드가 안넘어오고 있는 상황인데요!
클라이언트에서 공통적으로 `created_at` 필드를 사용해서 작성일자를 노출하고 있어서 해당 필드도 추가해주시면 좋을 것 같습니다!

관련 이슈: https://github.com/GooJinSun/WhoAmI-Today-frontend/issues/165

**이미지**
<img width="664" alt="스크린샷 2023-09-09 오전 11 07 23" src="https://github.com/GooJinSun/WhoAmI-Today-backend/assets/37523788/fd8bd7c5-4061-4c4a-85ed-da1e58b70bb1">

(참고: `api/feed/responses/:year/:month/:day/`에서는 잘 내려옵니다)
![스크린샷 2023-09-09 오전 11 12 00](https://github.com/GooJinSun/WhoAmI-Today-backend/assets/37523788/d49b7284-33ad-4ec4-ac80-9405b6473b78)

**테스트 환경**
데스크탑 / 모바일 / 브라우저 등

**Comment by h-yes-oo** [comment]
@GooJinSun 진선님 혹시 친구 피드의 경우 작성 일자를 created_at 이 아닌 date 기준으로 표시해주실 수 있나요 ?!

장고의 타임존 기능 상 모델 인스턴스의 created_at 이 인스턴스의 author 기준이 아닌 요청을 보낸 사람 기준 timezone 으로 내려오게 되어 있어서요, 
A 기준 9월 9일, B 기준 9월 10일인 시점에 A가 게시글을 작성하면 그 게시물을 A가 요청했을 때에는 created_at 이 9월 9일로 내려오고 B가 요청했을 때에는 created_at 이 9월 10일로 내려오게 됩니다. 모든 친구들이 해당 게시물의 작성일자를 A가 작성한 날짜인 9월 9일로 받을 수 있도록 date 필드를 만든 것이었어서 프론트에서 이슈가 없다면 date 기준으로 작성일자가 노출되면 좋을 것 같습니다..! 

검토해주시고 이슈 있다면 말씀 부탁드려요 감사합니다 (_ _)

**Comment by GooJinSun** [comment]
9/9 슬랙 논의 결과
https://whoami-today.slack.com/archives/C04N0LYHTNH/p1694234552955629?thread_ts=1694163619.821169&cid=C04N0LYHTNH
- 작성자가 아닌 사용자의 타임존을 기준으로 작성시간을 다음과 같이 노출
  - 방금 전
  - N분 전
  - N시간 전
  - 그 외(YYYY-MM-DD HH-mm-ss)

**Comment by njs03332** [comment]
아마도 #75 와 연관있는 듯함 !!
